### PR TITLE
Bump netty to latest

### PR DESCRIPTION
**Pull request by xIsm4**

### CODE REVIEW

**Comment by Electroid** [comment]
Thanks!

**Comment by theFoxley** [comment]
There is no issue with protocollib / packetevents with this version ?
6 months ago i tested with a version newer than 4.1.69 and i had issues, i'll test it this evening

**Comment by calcastor** [comment]
> There is no issue with protocollib / packetevents with this version ? 6 months ago i tested with a version newer than 4.1.69 and i had issues, i'll test it this evening

ProtocolLib 4.8.0 works fine with it.

**Comment by theFoxley** [comment]
yep sorry i tested it, it works with Protocollib 5.0 and packetevents too

**Comment by xIsm4** [comment]
> There is no issue with protocollib / packetevents with this version ? 6 months ago i tested with a version newer than 4.1.69 and i had issues, i'll test it this evening

Protocolib works with New versions and implementa netty methods. Shouldnt be a problem.

**Comment by theFoxley** [comment]
Yep it's perfectly fine, i even updated to netty-91, thanks

**Pull request merged**
