### PR TITLE
Fix "Chunk Patch" NPE

### PR DESCRIPTION
**Pull request by linsaftw**
Fixed a NPE caused by this patch.

### CODE REVIEW

**Comment by linsaftw** [comment]
Replace #69 "fix chunk npe" commit

**Review by LewUwU — APPROVED** [review]

**Comment by linsaftw** [comment]
"Fixed chunk NPE" - This checks a NPE in the chunk memory leak patch.
"Add update FastUtil patch" - Updates FastUtil library (This doesn't seem to fix the issue tho, but it's good to have latest)
"Patch NPE on FastUtil" - When iterating over LongSet it generates an exception, probably because something is getting removed at the same time we iterate.

Another fix would be reverting FastUtil.

**Comment by linsaftw** [comment]
Alright this "FastUtil" lib is not made for concurrent calls and it sometimes throws exceptions that the "item" doesn't exist or something similar.

I recommend just reverting the FastUtil patch instead.

**Comment by LewUwU** [comment]
This only happens on SportPaper custom unload chunk implementation since i use FastUtil in a lot of things (included chunks) in my InsanePaper fork and these errors doesn't happen

**Comment by linsaftw** [comment]
> This only happens on SportPaper custom unload chunk implementation since i use FastUtil in a lot of things (included chunks) in my InsanePaper fork and these errors doesn't happen

It crashed again. This seems to be an issue from FastUtil when concurrently modifying its collections.

To fix the issue it is required to remove FastUtil from everywhere, i will implement a commit soon.

**Comment by linsaftw** [comment]
Nah, seems a lot of parts of the code use FastUtil. So i might try just change the type of FastUtil collections used.

**Comment by linsaftw** [comment]
Alright i instead replaced the type of collection used on ChunkProviderServer. No crashes yet.

**Review by Electroid — APPROVED** [review]

**Comment by Pablete1234** [comment]
This patch makes chunk unloading O(n) by using a `LongArraySet` instead of being O(1), this means the server slows down considerably the more getChunk calls occur and the more chunks get on the unload queue, this had been fixed in https://github.com/Electroid/SportPaper/pull/19 and is a bug that got reintroduced in this pr

**Comment by yiatzz** [comment]
> This patch makes chunk unloading O(n) by using a `LongArraySet` instead of being O(1), this means the server slows down considerably the more getChunk calls occur and the more chunks get on the unload queue, this had been fixed in #19 and is a bug that got reintroduced in this pr
> 
> Next time when editing lines that already have a `// sportpaper` comment be more caureful about editing them and lookup the original patches to see why they were already changed, don't mindlessly override the previous changes

i can confirm it.

**Comment by linsaftw** [comment]
Thank you very much i will try to fix it asap.

**Comment by Pablete1234** [comment]
> Thank you very much i will try to fix it asap. Any recommendations?

Keep the patch in #19 as it was

**Comment by linsaftw** [comment]
> > Thank you very much i will try to fix it asap. Any recommendations?
> 
> Keep the patch in #19 as it was

thanks but i changed it because it caused errors for some reason

**Pull request merged**
