### PR TITLE
Simple Guice support

### PR DESCRIPTION
**Pull request by AustinLMayes**
Adds bare-bones guice plugin support based on the larger patch from SportBukkit. 

* Each plugin is it's own `ProtectedModule` where the `publicBinder()` is the global server binder
* `Server` is globally provided
* `Plugin` is provided inside each module and bound to the current containing plugin instance

__NOTE:__ This will fail to build until @Electroid sets up builds for [Ubique](https://github.com/StratusNetwork/Ubique)

### CODE REVIEW

**Comment by Electroid** [comment]
@AustinLMayes What are your thoughts on this? Still want Guice support?

**Comment by AustinLMayes** [comment]
@Electroid Yes, guice support at the server level is needed to support cross-plugin injection decently. This was just not merged since Ubique isn't in nexus and it would break the build.

**Comment by AustinLMayes** [comment]
We are no longer using Guice internally.

@Electroid Thoughts on merging this still to add support if anyone else needs it?

**Comment by Electroid** [comment]
Nah, it just complicates things.

**Pull request closed without merging**
